name: Zola
on: [push]

jobs:
  build-and-deploy:
    runs-on: native
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive  # <--- ESTA ES LA CLAVE

      - name: Construir sitio
        run: zola build

      - name: Nginx
        run: |
          rm -rf /var/www/alejandrogs.es/*
          cp -r public/* /var/www/alejandrogs.es/
